# This contains params to be used by the stages to train or predic

prepared:
  split: 0.2
  seed: 2021

featurize: 
  max_features: 2500
  ngrams: 3

train: 
  seed: 2021
  n_est: 110
  min_split: 32
  n_jobs: 2
