# This contains params to be used by the stages to train or predic

prepared:
  split: 0.3
  seed: 2021

featurize: 
  max_features: 3000
  ngrams: 2

train: 
  seed: 2021
  n_est: 100
  min_split: 16
  n_jobs: 2
