# add ci-cd steps here
name: DVC-PROJECT-NLP

on: [push]

jobs:
  run:
    run-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'

      - name: cml-run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: 
          #Your ML workflow cmds
          pip install --upgrade pip
          pip install -r rquirements.txt

          dvc repro -v 

          echo "# REPORTS" >> report.md
          echo "## metrics" >> report.md
          cat score.json >> report.md

          cml-send-comment report.md
